// Module 6 (Changelog & versioning). Hand-maintained by the release step —
// never regenerated by `npm run build`. Rule of thumb from STANDARD.md:
// "build validates, release generates." If a routine build ever needs to
// mutate this file to stay "fresh," that's the bug, not a fact of life —
// see scripts/release.mjs, which only stamps RELEASE_DATE when a human runs
// it deliberately, and never runs as part of `npm run build`.
export const APP_VERSION = "0.1.0";
export const RELEASE_DATE = "2026-08-19";

// Newest first. Keep entries short — this renders in Cuenta's changelog tab.
export const CHANGELOG = [
  {
    version: "0.1.0",
    date: "2026-08-19",
    notes: [
      "Primer lanzamiento multi-negocio de CtrlHQ: cada negocio (tenant) tiene sus propios Ingresos, Egresos, Nómina y Consumos de Equipo, aislados por RLS.",
      "Cuenta y zona de peligro: gestión de miembros, exportar datos, eliminar el negocio.",
      "Soporte y mejoras disponibles desde la app.",
    ],
  },
];
